version: '3.3'

services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - type: volume
        source: data
        target: /var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123!
    ports:
      - "1433:1433"

volumes:
  data: